/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Fabian Senn <fsenn@hsr.ch>
 */
public class _not_in_use_MainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form _not_in_use_MainJPanel
     */
    public _not_in_use_MainJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
     * The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblPlayerName = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        txtPlayerName = new javax.swing.JTextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        pnlSinglePlayer = new javax.swing.JPanel();
        lblSinglePlayer = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        pnlMultiPlayer = new javax.swing.JPanel();
        lblMultiPlayer = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 4), new java.awt.Dimension(0, 4), new java.awt.Dimension(32767, 4));
        btnCreateGame = new javax.swing.JButton();
        btnJoin = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        pnlControl = new javax.swing.JPanel();
        btnHelp = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnExit = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><h1>~ZeLaMoSe - Tetris~</h1></html>");
        add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><strong>Settings</strong></html>");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        lblPlayerName.setText("Player Name: ");
        jPanel3.add(lblPlayerName);
        jPanel3.add(filler5);

        txtPlayerName.setText("Player");
        txtPlayerName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(txtPlayerName);

        jPanel2.add(jPanel3);

        jPanel1.add(jPanel2);
        jPanel1.add(filler6);

        pnlSinglePlayer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlSinglePlayer.setLayout(new javax.swing.BoxLayout(pnlSinglePlayer, javax.swing.BoxLayout.Y_AXIS));

        lblSinglePlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSinglePlayer.setText("<html><strong>SinglePlayer</strong></html>");
        lblSinglePlayer.setAlignmentX(0.5F);
        pnlSinglePlayer.add(lblSinglePlayer);

        jButton2.setText("Start Game");
        jButton2.setAlignmentX(0.5F);
        jButton2.setBorderPainted(false);
        pnlSinglePlayer.add(jButton2);
        jButton2.getAccessibleContext().setAccessibleName("btnStartSinglePlayer");

        jPanel1.add(pnlSinglePlayer);
        jPanel1.add(filler3);

        pnlMultiPlayer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlMultiPlayer.setLayout(new javax.swing.BoxLayout(pnlMultiPlayer, javax.swing.BoxLayout.Y_AXIS));

        lblMultiPlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMultiPlayer.setText("<html><strong>MultiPlayer</strong></html>");
        lblMultiPlayer.setAlignmentX(0.5F);
        pnlMultiPlayer.add(lblMultiPlayer);
        pnlMultiPlayer.add(filler2);

        btnCreateGame.setText("Create Game");
        btnCreateGame.setAlignmentX(0.5F);
        btnCreateGame.setBorderPainted(false);
        pnlMultiPlayer.add(btnCreateGame);

        btnJoin.setText("Join Game");
        btnJoin.setAlignmentX(0.5F);
        btnJoin.setBorderPainted(false);
        pnlMultiPlayer.add(btnJoin);

        jPanel1.add(pnlMultiPlayer);
        jPanel1.add(filler4);

        pnlControl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlControl.setLayout(new javax.swing.BoxLayout(pnlControl, javax.swing.BoxLayout.LINE_AXIS));

        btnHelp.setText("Help");
        btnHelp.setBorderPainted(false);
        pnlControl.add(btnHelp);
        pnlControl.add(filler1);

        btnExit.setText("Exit");
        btnExit.setBorderPainted(false);
        pnlControl.add(btnExit);

        jPanel1.add(pnlControl);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateGame;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnJoin;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblMultiPlayer;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblSinglePlayer;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlMultiPlayer;
    private javax.swing.JPanel pnlSinglePlayer;
    private javax.swing.JTextField txtPlayerName;
    // End of variables declaration//GEN-END:variables
}
