/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import domain.TetrisController;
import java.rmi.registry.Registry;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import network.client.NetworkHandlerAbstract;

/**
 *
 * @author Fabian Senn <fsenn@hsr.ch>
 */
public class JoinGameJFrame extends javax.swing.JFrame implements Observer {
    private final GameType gameType;
    public enum GameType {SINGLE_PLAYER, MULTIPLAYER_HOST, MULTIPLAYER_JOIN};

    JoinGameJFrame(GameType gameType) {
        this.gameType = gameType;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConnection = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlConnectionLayout = new javax.swing.GroupLayout(pnlConnection);
        pnlConnection.setLayout(pnlConnectionLayout);
        pnlConnectionLayout.setHorizontalGroup(
            pnlConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
        pnlConnectionLayout.setVerticalGroup(
            pnlConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConnection, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConnection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlConnection;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        switch((TetrisController.UpdateType)o1) {
            case CONNECTION_ESTABLISHED:
                
                java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                //new JoinGameJFrame(tetrisController, tetrisController.).setVisible(true);
            }
        });
        this.dispose();
                break;
            case EXCEPTION_THROWN:
                JOptionPane.showInternalMessageDialog(this, "Program could not connect to Server", "Connection Establishment failed", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }
}
