/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.jogamp.opengl.util.FPSAnimator;
import domain.Config;
import domain.GameEngine;
import domain.SimulationStateAbstract;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Fabian Senn <fsenn@hsr.ch>
 */
public class OtherGameFieldJPanel extends javax.swing.JPanel implements Observer {

    private GameEngine observableEngine;

    /**
     * Creates new form OtherGameFieldJPanel
     */
    public OtherGameFieldJPanel(String playerName, SimulationStateAbstract observableEngine) {
        initComponents();
        this.observableEngine = (GameEngine)observableEngine;
        this.lblOtherPlayerName1.setText("<html><b>" + playerName + "</html></b>");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
     * The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gLPnlEnemyArea1 = new javax.media.opengl.awt.GLJPanel();
        lblOtherPlayerName1 = new javax.swing.JLabel();
        lblScore2 = new javax.swing.JLabel();
        lblOtherScoreValue1 = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblOtherLevel1 = new javax.swing.JLabel();
        lblNbrOfLines1 = new javax.swing.JLabel();
        lblOtherNumbersOfLines1 = new javax.swing.JLabel();
        lblNbrOfBlocks = new javax.swing.JLabel();
        lblOtherNumberOfBlocks1 = new javax.swing.JLabel();

        gLPnlEnemyArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gLPnlEnemyArea1.setMaximumSize(new java.awt.Dimension(120, 220));
        gLPnlEnemyArea1.setMinimumSize(new java.awt.Dimension(120, 220));

        javax.swing.GroupLayout gLPnlEnemyArea1Layout = new javax.swing.GroupLayout(gLPnlEnemyArea1);
        gLPnlEnemyArea1.setLayout(gLPnlEnemyArea1Layout);
        gLPnlEnemyArea1Layout.setHorizontalGroup(
            gLPnlEnemyArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );
        gLPnlEnemyArea1Layout.setVerticalGroup(
            gLPnlEnemyArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        lblOtherPlayerName1.setText("<OtherPlayerName1>");

        lblScore2.setText("<html><b>Score:</b></html>");
        lblScore2.setBorder(null);
        lblScore2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblScore2.setMaximumSize(new java.awt.Dimension(81, 21));
        lblScore2.setMinimumSize(new java.awt.Dimension(81, 21));
        lblScore2.setPreferredSize(new java.awt.Dimension(81, 21));

        lblOtherScoreValue1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOtherScoreValue1.setText("<OtherScoreValue1>");

        lblLevel.setText("<html><b>Level:</b></html>");
        lblLevel.setBorder(null);
        lblLevel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblLevel.setMaximumSize(new java.awt.Dimension(81, 21));
        lblLevel.setMinimumSize(new java.awt.Dimension(81, 21));
        lblLevel.setPreferredSize(new java.awt.Dimension(81, 21));

        lblOtherLevel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOtherLevel1.setText("<OtherLevel1>");

        lblNbrOfLines1.setText("<html><b>Number of Lines:</b></html>");
        lblNbrOfLines1.setBorder(null);
        lblNbrOfLines1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblNbrOfLines1.setMaximumSize(new java.awt.Dimension(81, 21));
        lblNbrOfLines1.setMinimumSize(new java.awt.Dimension(81, 21));
        lblNbrOfLines1.setPreferredSize(new java.awt.Dimension(81, 21));

        lblOtherNumbersOfLines1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOtherNumbersOfLines1.setText("<OtherNumbersOfLines1>");

        lblNbrOfBlocks.setText("<html><b>Number of Blocks:</b></html>");
        lblNbrOfBlocks.setBorder(null);
        lblNbrOfBlocks.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblNbrOfBlocks.setMaximumSize(new java.awt.Dimension(81, 21));
        lblNbrOfBlocks.setMinimumSize(new java.awt.Dimension(81, 21));
        lblNbrOfBlocks.setPreferredSize(new java.awt.Dimension(81, 21));

        lblOtherNumberOfBlocks1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOtherNumberOfBlocks1.setText("<OtherNumberOfBlock1>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gLPnlEnemyArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOtherNumberOfBlocks1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOtherScoreValue1)
                            .addComponent(lblLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOtherLevel1)
                            .addComponent(lblNbrOfLines1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOtherNumbersOfLines1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNbrOfBlocks, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblOtherPlayerName1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblOtherPlayerName1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gLPnlEnemyArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblScore2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOtherScoreValue1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOtherLevel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNbrOfLines1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOtherNumbersOfLines1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNbrOfBlocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblOtherNumberOfBlocks1))))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.media.opengl.awt.GLJPanel gLPnlEnemyArea1;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblNbrOfBlocks;
    private javax.swing.JLabel lblNbrOfLines1;
    private javax.swing.JLabel lblOtherLevel1;
    private javax.swing.JLabel lblOtherNumberOfBlocks1;
    private javax.swing.JLabel lblOtherNumbersOfLines1;
    private javax.swing.JLabel lblOtherPlayerName1;
    private javax.swing.JLabel lblOtherScoreValue1;
    private javax.swing.JLabel lblScore2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        lblOtherScoreValue1.setText(Integer.toString(observableEngine.getScore()));
        lblOtherLevel1.setText(Integer.toString(observableEngine.getLevel()));
        lblOtherNumbersOfLines1.setText(Integer.toString(observableEngine.getTotalRemovedLines()));
        lblOtherNumberOfBlocks1.setText(Integer.toString(observableEngine.getBlockCounter()));
    }

    public void initGLJPanel(SimulationStateAbstract gameEngine) {
        GameFieldRenderer rendererEnemyArea1 = new GameFieldRenderer(Config.EnemyGameFieldBlockSize, gameEngine, false);
        gLPnlEnemyArea1.addGLEventListener(rendererEnemyArea1);
        FPSAnimator animator1 = new FPSAnimator(gLPnlEnemyArea1, Config.frameRate, true);
        animator1.start();
    }
}
